# Generated by Django 3.1.1 on 2021-03-02 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=30, verbose_name='Lugar')),
                ('tiempo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('direccion', models.CharField(default='ENTRADA', max_length=30, verbose_name='Dirección')),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autorización')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.persona', verbose_name='Persona')),
            ],
        ),
    ]
