# Generated by Django 3.1.7 on 2021-04-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradageneral',
            options={'verbose_name': 'Entrada General', 'verbose_name_plural': 'Entradas Generales'},
        ),
    ]
