# Generated by Django 3.1.4 on 2020-12-10 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20201210_1036'),
        ('registroGeneral', '0002_auto_20201209_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradageneral',
            name='direccion',
            field=models.CharField(default='ENTRADA', max_length=30, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='entradageneral',
            name='lugar',
            field=models.CharField(max_length=30, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='entradageneral',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='entradageneral',
            name='tiempo',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
    ]
