# Generated by Django 3.1.1 on 2020-11-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0002_auto_20201118_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradageneral',
            name='tiempo',
            field=models.DateTimeField(default='2020-11-18 10:17:34'),
        ),
    ]
