# Generated by Django 3.1.7 on 2021-04-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0002_auto_20210413_1652'),
        ('registroGeneral', '0002_auto_20210413_1752'),
    ]

    operations = [
    ]
