# Generated by Django 3.1.1 on 2020-11-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0003_auto_20201118_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradageneral',
            name='direccion',
            field=models.CharField(default='ENTRADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='entradageneral',
            name='tiempo',
            field=models.DateTimeField(default='2020-11-27 09:40:16'),
        ),
    ]
