# Generated by Django 3.1.4 on 2020-12-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0003_auto_20201210_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradageneral',
            name='autorizado',
            field=models.BooleanField(default=False, verbose_name='Autorización'),
        ),
    ]
