# Generated by Django 3.1.3 on 2020-11-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0003_auto_20201124_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradageneral',
            name='tiempo',
            field=models.DateTimeField(default='2020-11-24 13:35:57'),
        ),
    ]
