# Generated by Django 3.1.3 on 2020-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0004_auto_20201124_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradageneral',
            name='tiempo',
            field=models.DateTimeField(default='2020-11-24 13:40:30'),
        ),
    ]
