# Generated by Django 3.1.1 on 2020-12-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0004_auto_20201127_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradageneral',
            name='tiempo',
            field=models.DateTimeField(default='2020-12-03 11:59:34'),
        ),
    ]
