# Generated by Django 3.1.1 on 2020-12-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0005_auto_20201203_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradageneral',
            name='tiempo',
            field=models.DateTimeField(default='2020-12-07 15:34:12'),
        ),
    ]
