# Generated by Django 3.1.3 on 2020-11-24 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0005_auto_20201124_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradageneral',
            name='tiempo',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 13, 50, 2, 713344, tzinfo=utc)),
        ),
    ]
