# Generated by Django 3.1.3 on 2020-11-24 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0006_auto_20201124_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradageneral',
            name='tiempo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
