# Generated by Django 3.1.1 on 2020-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0007_auto_20201209_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradageneral',
            name='tiempo',
            field=models.DateTimeField(default='2020-12-09 11:26:14'),
        ),
    ]
