# Generated by Django 3.1.3 on 2020-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroGeneral', '0010_auto_20201124_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradageneral',
            name='entra',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entradageneral',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
