# Generated by Django 3.1.2 on 2020-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoSocio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=30, verbose_name='Nombre y Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('nrTarjeta', models.IntegerField(verbose_name='Nr. de Tarjeta')),
                ('nrSocio', models.IntegerField(blank=True, null=True, verbose_name='Nr. de Socio')),
                ('general', models.BooleanField(default=False)),
                ('pileta', models.BooleanField(default=False)),
                ('tenis', models.BooleanField(default=False)),
            ],
        ),
    ]
