# Generated by Django 3.1.6 on 2021-03-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='deuda',
            field=models.FloatField(default=0, null=True, verbose_name='Deuda'),
        ),
    ]
