# Generated by Django 3.1.1 on 2020-11-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nrTarjeta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
