# Generated by Django 3.1.1 on 2020-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSocio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='deuda',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_apellido',
            field=models.CharField(max_length=30, verbose_name='Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nrSocio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nr. de Socio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nrTarjeta',
            field=models.IntegerField(verbose_name='Nr. de Tarjeta'),
        ),
    ]
