# Generated by Django 3.1.3 on 2020-11-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20201124_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nrTarjeta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nr. de Tarjeta'),
        ),
    ]
