# Generated by Django 3.1.1 on 2020-11-05 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_persona_nrtarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='tiempo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
