# Generated by Django 3.1.1 on 2020-11-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20201113_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='deuda',
            field=models.FloatField(null=True),
        ),
    ]
