# Generated by Django 3.1.5 on 2021-02-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20201210_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='deuda',
            field=models.FloatField(default=300),
        ),
    ]
