# Generated by Django 3.1.1 on 2020-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20201203_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='deuda',
            field=models.IntegerField(),
        ),
    ]
