# Generated by Django 3.1.1 on 2020-12-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20201209_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='deuda',
            field=models.FloatField(),
        ),
    ]
