# Generated by Django 3.1.7 on 2021-03-19 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProveedor', models.CharField(max_length=30, verbose_name='idProveedor')),
                ('nombre_proveedor', models.CharField(max_length=30, verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo')),
                ('noSocio', models.IntegerField(null=True, verbose_name='DNI')),
                ('lugar', models.CharField(max_length=30, verbose_name='Lugar')),
                ('tiempo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('direccion', models.CharField(default='ENTRADA', max_length=30, verbose_name='Dirección')),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autorización')),
                ('cicloCaja', models.IntegerField(null=True, verbose_name='cicloCaja')),
                ('cicloMensual', models.IntegerField(null=True, verbose_name='cicloMensual')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.persona', verbose_name='Persona')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.proveedor', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Cobros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(verbose_name='precio')),
                ('registroEstacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.registro_estacionamiento', verbose_name='registroEstacionamiento')),
            ],
        ),
    ]
