# Generated by Django 3.1.7 on 2021-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cicloanual',
            options={'verbose_name': 'Ciclo Anual', 'verbose_name_plural': 'Ciclos Anuales'},
        ),
        migrations.AlterModelOptions(
            name='ciclocaja',
            options={'verbose_name': 'Ciclo Caja', 'verbose_name_plural': 'Ciclos Caja'},
        ),
        migrations.AlterModelOptions(
            name='ciclomensual',
            options={'verbose_name': 'Ciclo Mensual', 'verbose_name_plural': 'Ciclos Mensuales'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='registroestacionamiento',
            options={'verbose_name': 'Registro Estacionamiento', 'verbose_name_plural': 'Registros Estacionamiento'},
        ),
        migrations.AddField(
            model_name='cobros',
            name='deuda',
            field=models.BooleanField(default=False, verbose_name='deuda'),
        ),
    ]
