# Generated by Django 3.1.7 on 2021-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cicloCaja', models.IntegerField(verbose_name='cicloCaja')),
            ],
        ),
        migrations.CreateModel(
            name='CicloMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cicloMensual', models.IntegerField(verbose_name='cicloMensual')),
            ],
        ),
        migrations.RenameModel(
            old_name='Registro_Estacionamiento',
            new_name='RegistroEstacionamiento',
        ),
    ]
