# Generated by Django 3.1.7 on 2021-03-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('estacionamiento', '0002_auto_20210319_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.proveedor', verbose_name='Proveedor'),
        ),
    ]
