# Generated by Django 3.1.7 on 2021-04-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0003_merge_20210419_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(choices=[('FALTA REGISTRO ENTRADA', 'FALTA REGISTRO ENTRADA'), ('CONFLICTO', 'CONFLICTO')], max_length=30, verbose_name='razon')),
                ('comentario', models.CharField(blank=True, max_length=300, null=True, verbose_name='comentario')),
            ],
            options={
                'verbose_name': 'AperturaManual',
                'verbose_name_plural': 'AperturasManuales',
            },
        ),
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='tipo',
            field=models.CharField(choices=[('SOCIO', 'SOCIO'), ('SOCIO-MOROSO', 'SOCIO-MOROSO'), ('NOSOCIO', 'NOSOCIO'), ('PROVEEDOR', 'PROVEEDOR'), ('MANUAL', 'MANUAL')], default='SOCIO', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='registroestacionamiento',
            name='apertuaManual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.aperturamanual', verbose_name='AperturaManual'),
        ),
    ]
