# Generated by Django 3.1.6 on 2021-03-20 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0003_auto_20210319_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.proveedor', verbose_name='Proveedor'),
        ),
    ]
