# Generated by Django 3.1.7 on 2021-04-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0004_auto_20210420_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturamanual',
            name='direccion',
            field=models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA')], default='ENTRADA', max_length=30, verbose_name='Dirección'),
        ),
    ]
