# Generated by Django 3.1.6 on 2021-03-20 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('estacionamiento', '0004_auto_20210320_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='noSocio',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.persona', verbose_name='Persona'),
        ),
    ]
