# Generated by Django 3.1.6 on 2021-03-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0005_auto_20210320_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroestacionamiento',
            name='identificador',
            field=models.CharField(default=12, max_length=30, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
