# Generated by Django 3.1.6 on 2021-03-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0006_registroestacionamiento_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='identificador',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Identificador'),
        ),
    ]
