# Generated by Django 3.1.6 on 2021-03-23 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0007_auto_20210320_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroestacionamiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='registroestacionamiento',
            name='tiempo',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
        ),
    ]
