# Generated by Django 3.1.7 on 2021-03-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa_mod',
            name='day',
        ),
        migrations.AlterField(
            model_name='tarifa_mod',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tarifa_mod',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
